name = "LaserFields"
uuid = "dfcd5af1-1e31-431a-b1a1-3c72ddca0e1b"
authors = ["Johannes Feist <johannes.feist@gmail.com> and contributors"]
version = "0.1.6"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
DataInterpolations = "3, 4, 5, 6"
DelimitedFiles = "1"
SnoopPrecompile = "1"
SpecialFunctions = "2"
julia = "1.6"
